### ISSUE TITLE
[BUG] Could not pass event InventoryClickEvent to CustomItems v4.0.2 org.bukkit.event.EventException: null

### ISSUE THREAD

**Issue by shobzane** [jojodmo/CustomItems#11]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain your Bug / Issue

Hi! I just bought the plugin and get this error whenever I try to click the Add a trigger button in the GUI.

![errors](https://user-images.githubusercontent.com/28008531/129968004-6022c39d-dec2-48c2-aae0-c8f9c84d5f7b.PNG)

### Minecraft Version

1.17.1

### Plugin Version

v4.0.2

### Server log.

https://paste.gg/p/anonymous/5ef8be1a94d640669a1ba63b50d4e631

### Anything else?

![errors](https://user-images.githubusercontent.com/28008531/129968137-c9babc5b-d4e8-4c45-9c4f-17beb3a58e42.PNG)

**Comment by jojodmo** [comment]
Thank you for the bug report! Version 4.0.3 on Polymart fixes this issue: https://polymart.org/resource/custom-items.1/updates?update=6887
