### ISSUE TITLE
[BUG] Actions Null null ?

### ISSUE THREAD

**Issue by n54b** [jojodmo/CustomItems#12]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain your Bug / Issue

a picture is worth more than 1000 words 
![image](https://user-images.githubusercontent.com/12047619/130857095-373b26d6-001b-4163-8b99-2d5a3311cc3e.png)

### Minecraft Version

1.16.5

### Plugin Version

4.0.3

### Server log.

https://paste.gg/p/anonymous/6b415210e0ea4281b2262557a4b52d34

### Anything else?

I think that all :)

**Comment by jojodmo** [comment]
Thank you for your bug report! This issue should now be fixed in version 4.0.10: https://polymart.org/resource/custom-items.1/updates?update=7784

Please let me know if you have any questions!
