### ISSUE TITLE
[BUG] Can't enchant and forge custom armor

### ISSUE THREAD

**Issue by Fantaster142** [jojodmo/CustomItems#14]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain your Bug / Issue

I have created a custom armor, its an "emerald" armor make of dyed leather armor.
When i try to enchant it in the enchantment table there is no enchanting options and when i put it in the anvil i can't puts enchanted books and if i forge the armor with nothing the armor get rename as a simple leather armor and is not count as a custom item.

Here's the file for the chesplate of my armor for exemple : https://paste.gg/p/anonymous/ed766dc02e07430bac5dc9fb3ca4a5fc

I don't have errors in the console.

### Minecraft Version

1.8.8

### Plugin Version

4.0.7

### Server log.

https://paste.gg/p/anonymous/ccb369fdd5ef406f861592c5ac720043

**Comment by Fantaster142** [comment]
news ?

**Comment by natr566** [comment]
1.8 is redundant so it is unlikely these bugs will be fixed. But please make new bug reports on the discord.
