### ISSUE TITLE
[BUG] The custom item is used even though there is a cooldown

### ISSUE THREAD

**Issue by Fantaster142** [jojodmo/CustomItems#15]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain your Bug / Issue

I have this custom item : https://paste.gg/p/anonymous/46562faac8e247919f694d83732a440e
Which is a consumable item that gives regen effect.

The problem is when i whant to consume this item when i am in cooldown and look in a block the item in consume when it should not be, and it give an error in the console which i put bellow in server log.

### Minecraft Version

1.8.8

### Plugin Version

4.0.7

### Server log.

https://paste.gg/p/anonymous/68d439331b804dbfa7a02a61b0de20fd

**Comment by Fantaster142** [comment]
news ?

**Comment by natr566** [comment]
1.8 is redundant so it is unlikely these bugs will be fixed. But please make new bug reports on the discord.
