### ISSUE TITLE
[BUG] Custom bloc drops glitched

### ISSUE THREAD

**Issue by Fantaster142** [jojodmo/CustomItems#16]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain your Bug / Issue

I have created a minerium ore that use a block of sponge, i set it to drop minerium fragment an other custom item that i created but instead of droping this it instant drop the block of sponge.

### Minecraft Version

1.8.8

### Plugin Version

4.0.7

### Server log.

https://paste.gg/p/anonymous/d0c4f4dddc644d5dbe12cfa1f0fe912f

**Comment by Fantaster142** [comment]
hello, do you have news about the bugs fixes ?

**Comment by natr566** [comment]
1.8 is redundant so it is unlikely these bugs will be fixed. But please make new bug reports on the discord.
