### ISSUE TITLE
[FEATURE-REQUEST] specific line for SetItemLore action

### ISSUE THREAD

**Issue by Fantaster142** [jojodmo/CustomItems#17]
### Is your feature request related to a problem? Please describe.

I would like to set a specific line of the lore with the action SetItemLore, not recreate an entire lore.
It would be great if you add this :)

**Comment by jojodmo** [comment]
Great suggestion! This has been added in version 4.0.13: https://polymart.org/resource/custom-items.1/updates?update=7985
