### ISSUE TITLE
[Server Crash] Keeps Crashing

### ISSUE THREAD

**Issue by Densaceous** [jojodmo/CustomItems#18]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain your Bug / Issue

Every time I try and add the plugin, it crashes my server.

### Minecraft Version

1.17.1

### Plugin Version

4.0.5

### Server log.

https://paste.gg/p/anonymous/60b45c04664b4238aa98a8a68906fd88

**Comment by n54b** [comment]
Did you read the error ?

<html><body>
<pre class="file-source no-highlight hljs" id="bacaeefd06274b42a0780f0a1f053457" data-ln-prefix="pastefile1">

  | [00:10:52] [Server thread/INFO]:     ----=========================----
-- | --
  | [00:10:52] [Server thread/INFO]:    CustomItems now requires CustomUniverse (free).
  | [00:10:52] [Server thread/INFO]:    Download CustomUniverse for free at https://spigotmc.org/resources/94544/
  | [00:10:52] [Server thread/INFO]:     ----=========================----
  | [00:10:52] [Server thread/INFO]:
  | [00:10:52] [Server thread/INFO]: CustomUniverse allows CustomItems to hook in with other plugins, making your server even more customizable. For example, it allows you to share global variables between plugins.
  | [00:10:52] [Server thread/INFO]: Download CustomUniverse for free at https://spigotmc.org/resources/94544/
  | [00:10:52] [Server thread/INFO]: Stopping the server to prevent damage...

</pre>
</body>
</html>

**Comment by natr566** [comment]
Install CustomUniverse > https://polymart.org/r/customuniverse.1220
