### ISSUE TITLE
[FEATURE-REQUEST] RESIDENCE SUPPORT

### ISSUE THREAD

**Issue by gazdyy** [jojodmo/CustomItems#19]
### Is your feature request related to a problem? Please describe.

I use various actions in items such as teleportTarget for handler projectileHitMob but I don't want players to be able to steal other monsters from their protected area

### Describe the solution you'd like

Add support for the residence plugin. If a player is in another player's protected area, no handlers or their actions will work for him when using the item

### Anything else?

residence plugin: https://www.spigotmc.org/resources/residence-1-7-10-up-to-1-17.11480/

**Comment by natr566** [comment]
Not sure if this will be added but Please request on the discord. Thanks
