### ISSUE TITLE
[BUG] <Texture gen>

### ISSUE THREAD

**Issue by doragoma** [jojodmo/CustomItems#20]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Explain your Bug / Issue

https://cdn.discordapp.com/attachments/524487963804041217/887934144385019944/CustomItems_RP.zip
I know that below 1.13 is beta
When I made a texture, I tried to use the file that was created, but it wouldn't fit, so I couldn't use it.

### Minecraft Version

1.12.2

### Plugin Version

4.0.7

**Comment by natr566** [comment]
Please make new bug reports on the discord. as auto texture gen below 1.14 is highly unstable.
