### ISSUE TITLE
/cui list only shows 5 items

### ISSUE THREAD

**Issue by moonarts** [jojodmo/CustomItems#23]
I have been creating custom items via .yml files.
But when I have more than 5 in the plugins/CustomItems/Items folder, it shows only 5 in the "/cui list." command

When I try to create more than 5 custom items via the in game "/cui create id" command, I can see it properly in the list.

**Comment by natr566** [comment]
Can you provide the output of /cui version 
And What Minecraft version you are using
Thanks

**Comment by natr566** [comment]
Inactive, Cant Prove
