### ISSUE TITLE
Do i buy this?

### ISSUE THREAD

**Issue by MGW14** [jojodmo/CustomItems#4]
I am not really sure if i want to buy this, because im only intereseted in the Custom Blocks Feature.
(Is it possible to disable the other features?)
Is it possible to only use the api so i don't have any Ingame commands?
Thanks for your help!

**Comment by jojodmo** [comment]
Sorry about the long response time! Yeah! It's totally possible to not use any of the item features and only use the block features, and also to just use the API so you don't need to use ingame commands!
