### ISSUE TITLE
Could not pass event PlayerInteractEvent

### ISSUE THREAD

**Issue by Blowing-up-time** [jojodmo/CustomItems#5]
I started using this plugin and i was trying to make a wand that when you right click, it shoots a fireball and has a chance to consume ammo (blaze powder) when used.
when i added the "playerRemoveItem" action, it comes up with the error "Could not pass event PlayerInteractEvent to CustomItems 2.7.3"
I'm using spigot 1.8.9 so that might be doing something and i dont think it's anything with the handlers. If it's something with my handlers code let me know. Any help would be appreciated.

Code for the handlers is attached
[handlers.txt](https://github.com/jojodmo/CustomItems/files/3977228/handlers.txt)

**Comment by jojodmo** [comment]
Thanks for your report! Could you please try updating to the latest version of Custom Items? (which may not fix the issue, but just incase it does, might as well try). If that does nothing, could you send me the entire error log you get in the console? It will help me narrow down the issue. Thanks!

**Comment by Blowing-up-time** [comment]
still got an error. its not the "Player interact event" but now its about there being "expected <block end>, but found BlockSequenceStart". is there a specific thing im missing because its the exact same as on the wiki and on spigot

**Comment by jojodmo** [comment]
Thanks for your message! There's a good chance that's a bug in the plugin... could you send me the entire error log you get in the console? It will help me narrow down and fix the issue. Thanks!

**Comment by Blowing-up-time** [comment]
[custom items log.txt](https://github.com/jojodmo/CustomItems/files/4039239/custom.items.log.txt)

**Comment by Blowing-up-time** [comment]
so i fixed my code on the item but im now back to the original problem with could not pass PlayerInteractEvent to customitems.

**Comment by Blowing-up-time** [comment]
heres the log
[custom items log.txt](https://github.com/jojodmo/CustomItems/files/4051750/custom.items.log.txt)

**Comment by natr566** [comment]
If this is still an issue please raise a new issue report
