### ISSUE TITLE
Server stops when customitems is installed

### ISSUE THREAD

**Issue by BenRulez** [jojodmo/CustomItems#9]
When i have Custom Items installed my server just... stops. It loads all my plugins, even customitems with no problems, then when i get the "Done! For help, type "help"" message the server just stops itself no error messages or anything it just stops, server works perfectly fine when i remove customitems.jar

**Comment by natr566** [comment]
Starting  06/08/2021, CustomUniverse (free) is a dependency for CustomItems. Your server will automatically shut down if you try to start it up without CustomUniverse installed. This is to prevent any damage that might occur if people unknowingly start their server with CustomItems disabled.

Download CustomUniverse for free from Polymart from (https://polymart.org/r/customuniverse.1220)

If you have this installed please let me know and we will look into it further.

**Comment by BenRulez** [comment]
that was it, thanks 
maybe update your spigot page and installation guide to say its required?
